<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Accedi</name>
   <tag></tag>
   <elementGuidId>2acd91ab-a517-411a-be33-b53655ba0474</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-bind</name>
      <type>Main</type>
      <value>menu.loginSignin.label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-login-label ng-binding</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accedi</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;ng-scope&quot;]/body[@class=&quot;page-it&quot;]/main-view[@class=&quot;os-windows browser-chrome device-unknown&quot;]/navigation[@class=&quot;ng-scope ng-isolate-scope is-loaded cookie-disc&quot;]/div[@class=&quot;main-header ng-scope&quot;]/a[@class=&quot;header-login ng-scope&quot;]/span[@class=&quot;header-login-label ng-binding&quot;]</value>
   </webElementProperties>
</WebElementEntity>
